/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CalendarForMobile: typeof import('./src/components/scheduler/CalendarForMobile.vue')['default']
    CalendarForPC: typeof import('./src/components/scheduler/CalendarForPC.vue')['default']
    CarouselComponent: typeof import('./src/components/nowPlaying/CarouselComponent.vue')['default']
    CarouselView: typeof import('./src/components/nowPlaying/CarouselView.vue')['default']
    DateBlock: typeof import('./src/components/scheduler/DateBlock.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    EventChips: typeof import('./src/components/scheduler/EventChips.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FilmCard: typeof import('./src/components/FilmCard.vue')['default']
    FilmInfo: typeof import('./src/components/filmDetails/FilmInfo.vue')['default']
    FilmNav: typeof import('./src/components/filmDetails/FilmNav.vue')['default']
    FullCalendar: typeof import('./src/components/Playing_calendar/FullCalendar.vue')['default']
    HorizontalSchedule: typeof import('./src/components/Playing_calendar/HorizontalSchedule.vue')['default']
    ImgSlider: typeof import('./src/components/filmDetails/ImgSlider.vue')['default']
    LikedList: typeof import('./src/components/likedfilms/LikedList.vue')['default']
    LikedPageHeader: typeof import('./src/components/likedfilms/LikedPageHeader.vue')['default']
    ListItem: typeof import('./src/components/nowPlaying/ListItem.vue')['default']
    ListPageHeader: typeof import('./src/components/nowPlaying/ListPageHeader.vue')['default']
    ListView: typeof import('./src/components/nowPlaying/ListView.vue')['default']
    MobileNav: typeof import('./src/components/navbar/MobileNav.vue')['default']
    PCNav: typeof import('./src/components/navbar/PCNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreeningCard: typeof import('./src/components/Playing_calendar/ScreeningCard.vue')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    ShowtimeList: typeof import('./src/components/ShowtimeList.vue')['default']
    VerticalSchedule: typeof import('./src/components/Playing_calendar/VerticalSchedule.vue')['default']
  }
}
