/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: (typeof import('primevue/calendar'))['default']
    CalendarForMobile: typeof import('./src/components/scheduler/CalendarForMobile.vue')['default']
    CalendarForPC: typeof import('./src/components/scheduler/CalendarForPC.vue')['default']
    CarouselComponent: typeof import('./src/components/category_list/CarouselComponent.vue')['default']
    CategoryCard: typeof import('./src/components/category_list/CategoryCard.vue')['default']
    DateBlock: typeof import('./src/components/scheduler/DateBlock.vue')['default']
    Dialog: (typeof import('primevue/dialog'))['default']
    Divider: typeof import('primevue/divider')['default']
    EventChips: typeof import('./src/components/scheduler/EventChips.vue')['default']
    EventSchedule: typeof import('./src/components/event_calendar/EventSchedule.vue')['default']
    FieldSet: typeof import('./src/components/liked_films/FieldSet.vue')['default']
    FilmCardSquare: typeof import('./src/components/category_list/FilmCardSquare.vue')['default']
    LikedList: typeof import('./src/components/liked_films/LikedList.vue')['default']
    LikedPageHeader: typeof import('./src/components/liked_films/LikedPageHeader.vue')['default']
    MobileNav: typeof import('./src/components/navbar_in_layouts/MobileNav.vue')['default']
    Password: (typeof import('primevue/password'))['default']
    PCNav: typeof import('./src/components/navbar_in_layouts/PCNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreeningCard: typeof import('./src/components/event_calendar/ScreeningCard.vue')['default']
    ScrollPanel: (typeof import('primevue/scrollpanel'))['default']
    ShowtimeList: typeof import('./src/components/ShowtimeList.vue')['default']
    Sidebar: (typeof import('primevue/sidebar'))['default']
    Splitter: (typeof import('primevue/splitter'))['default']
    TimelineNav: typeof import('./src/components/event_calendar/TimelineNav.vue')['default']
  }
}
